name: IT_Way_BD
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.2
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.20.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.jpg"
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
